service: sls-cms-server-app

provider:

  stage: brian # TODO paramterize 

  name: aws
  runtime: nodejs8.10
  memorySize: 512
  environment:
    COOKIE_SECRET: hello
    DB_PASSWORD: cedrus123 # TODO: use AWS secrets manager + rotate db uname/password
    DB_HOST: database-1.cluster-cwlp89mdindv.us-east-1.rds.amazonaws.com  # TODO fetch dynamically
    DB_USER: admin
    NODE_ENV: deployedEnv

region: eu-east-1

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
    timeout: 15 #  very high bc cold starts are slow with lambda in VPC + auroura sls may be in sleep mode depending on settings

    vpc:  # TODO make this dynamic based on acct / environment
      securityGroupIds:
        - sg-fb5c258d  
      subnetIds:
        - subnet-755c4a11
        - subnet-cd694bf2
        - subnet-8adeefa5
